import { execa } from 'execa';
import chalk from 'chalk';
import fs from 'fs/promises';
import path from 'path';

export async function setupMaterialUI(projectName, languageChoice) {
  console.log(chalk.blue('Setting up Material UI...'));
  process.chdir(projectName);

  try {
    // Install MUI and its peer dependencies
    console.log(chalk.blue('Installing @mui/material, @emotion/react, @emotion/styled...'));
    await execa('npm', ['install', '@mui/material', '@emotion/react', '@emotion/styled'], { stdio: 'inherit' });
    // Install sonner for toast notifications
    console.log(chalk.blue('Installing toast component...'));
    await execa('npm', ['install', 'sonner'], { stdio: 'inherit' });

    // Create providers directory and MUI ThemeProvider
    const providersDir = path.join(process.cwd(), 'src', 'app', 'providers');
    try { await fs.mkdir(providersDir, { recursive: true }); } catch {}
    const fileExt = languageChoice === 'ts' ? 'tsx' : 'js';
    const muiProviderPath = path.join(providersDir, `MuiProvider.${fileExt}`);
    const muiProviderContent = languageChoice === 'ts'
      ? `"use client"
import * as React from "react";
import { ThemeProvider, CssBaseline, createTheme } from "@mui/material";
import type { ReactNode } from "react";

const theme = createTheme({
  palette: {
    mode: "light",
    primary: { main: "#1976d2" },
    secondary: { main: "#9c27b0" },
  },
});

export function MuiProvider({ children }: { children: ReactNode }) {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      {children}
    </ThemeProvider>
  );
}
`
      : `"use client"
import * as React from "react";
import { ThemeProvider, CssBaseline, createTheme } from "@mui/material";

const theme = createTheme({
  palette: {
    mode: "light",
    primary: { main: "#1976d2" },
    secondary: { main: "#9c27b0" },
  },
});

export function MuiProvider({ children }) {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      {children}
    </ThemeProvider>
  );
}
`;
    await fs.writeFile(muiProviderPath, muiProviderContent, 'utf8');

    // Create toast component
    const componentsDir = path.join(process.cwd(), 'src', 'components');
    try { await fs.mkdir(componentsDir, { recursive: true }); } catch {}
    const uiComponentsDir = path.join(componentsDir, 'ui');
    try { await fs.mkdir(uiComponentsDir, { recursive: true }); } catch {}
    const toasterPath = path.join(uiComponentsDir, `toaster.${fileExt}`);
    const toasterContent = `"use client"\nimport { Toaster as SonnerToaster } from "sonner";\nexport function Toaster() {\n  return (<SonnerToaster position=\"top-right\" richColors closeButton className=\"z-50\" />);\n}\n`;
    await fs.writeFile(toasterPath, toasterContent, 'utf8');

    // Update layout to wrap with MuiProvider and add Toaster
    const layoutPath = `src/app/layout.${fileExt}`;
    let layoutContent = await fs.readFile(layoutPath, 'utf8');
    if (!layoutContent.includes('import { MuiProvider }')) {
      const importRegex = /^import .+?;/gm;
      let match, lastImportIndex = 0;
      while ((match = importRegex.exec(layoutContent)) !== null) {
        lastImportIndex = match.index + match[0].length;
      }
      const muiImport = 'import { MuiProvider } from "@/app/providers/MuiProvider";';
      layoutContent = lastImportIndex > 0
        ? layoutContent.slice(0, lastImportIndex) + '\n' + muiImport + layoutContent.slice(lastImportIndex)
        : muiImport + '\n' + layoutContent;
    }
    if (!layoutContent.includes('<MuiProvider>')) {
      layoutContent = layoutContent.replace('{children}', '<MuiProvider>{children}</MuiProvider>');
    }
    if (!layoutContent.includes('import { Toaster }')) {
      const importRegex = /^import .+?;/gm;
      let match, lastImportIndex = 0;
      while ((match = importRegex.exec(layoutContent)) !== null) {
        lastImportIndex = match.index + match[0].length;
      }
      const toasterImport = 'import { Toaster } from "@/components/ui/toaster";';
      layoutContent = lastImportIndex > 0
        ? layoutContent.slice(0, lastImportIndex) + '\n' + toasterImport + layoutContent.slice(lastImportIndex)
        : toasterImport + '\n' + layoutContent;
    }
    if (!layoutContent.includes('<Toaster />')) {
      if (layoutContent.includes('</body>')) {
        layoutContent = layoutContent.replace('</body>', '        <Toaster />\n      </body>');
      } else if (layoutContent.includes('</MuiProvider>')) {
        layoutContent = layoutContent.replace('</MuiProvider>', '  <Toaster />\n</MuiProvider>');
      }
    }
    // Update page title
    if (layoutContent.includes('title:') && layoutContent.includes('metadata')) {
      layoutContent = layoutContent.replace(/title: ["']Create Next App["']/, 'title: "HackPack Turbo — Build Fast, Ship Faster"');
      if (layoutContent.includes('description:')) {
        layoutContent = layoutContent.replace(/description: ["']Generated by create next app["']/, 'description: "Web application created with HackPack"');
      }
    }
    await fs.writeFile(layoutPath, layoutContent);

    // Create a welcome page similar to daisyUI, using MUI Button/Badge
    const pagePath = `src/app/page.${fileExt}`;
    const pageContent = fileExt === 'js' ? `"use client"
import { Button, Box, Container, Typography, Chip, Divider, Stack } from "@mui/material";
import { useState } from "react";
import { toast } from "sonner";

export default function Home() {
  const [count, setCount] = useState(0);
  const handleClick = () => {
    setCount(count + 1);
    toast.success("Success!", {
      description: "You've installed Material UI with HackPack 🚀",
    });
  };
  return (
    <Box minHeight="100vh" display="flex" alignItems="center" justifyContent="center" sx={{ background: 'linear-gradient(to bottom, #1976d2, #9c27b0)' }} >
      <Container maxWidth="sm" sx={{ bgcolor: '#', opacity:0.9, borderRadius: 2, boxShadow: 2, py: 6, px: 4, textAlign: 'center' }}>
        <Typography variant="h3" fontWeight="bold" mb={2} color="primary.secondary" sx={{opacity: 0.9}}>
          Welcome to <Box component="span" color="secondary.main">HackPack</Box>
        </Typography>
        <Typography variant="body1" mb={3} color="text.secondary">
          Build Fast, Ship Faster! 🚀<br />This project is set up with Next.js and Material UI.
        </Typography>
        <Button variant="contained" color="primary" size="large" onClick={handleClick} sx={{ mb: 3 }}>
          Click me for a toast notification: {count}
        </Button>
        <Stack direction="row" spacing={2} justifyContent="center" mb={2} mt={2}>
          <Chip label="Material UI" color="primary" />
          <Chip label="Next.js" color="secondary" />
          <Chip label="HackPack" color="success" />
        </Stack>
        <Divider sx={{ my: 2 }} />
        <Typography variant="caption" color="#030303">
          Edit <Box component="span" color={"#030303"} sx={{ bgcolor: 'grey.500', p: 0.5, borderRadius: 1 }}>src/app/page.tsx</Box> to get started
        </Typography>
      </Container>
    </Box>
  );
}
`
: `"use client"
import { Button, Box, Container, Typography, Chip, Divider, Stack } from "@mui/material";
import { useState } from "react";
import { toast } from "sonner";

export default function Home() {
  const [count, setCount] = useState(0);
  const handleClick = () => {
    setCount(count + 1);
    toast.success("Success!", {
      description: "You've installed Material UI with HackPack 🚀",
    });
  };
  return (
    <Box minHeight="100vh" display="flex" alignItems="center" justifyContent="center" sx={{ background: 'linear-gradient(to bottom, #1976d2, #9c27b0)' }} >
      <Container maxWidth="sm" sx={{ bgcolor: '#', opacity:0.9, borderRadius: 2, boxShadow: 2, py: 6, px: 4, textAlign: 'center' }}>
        <Typography variant="h3" fontWeight="bold" mb={2} color="primary.secondary" sx={{opacity: 0.9}}>
          Welcome to <Box component="span" color="secondary.main">HackPack</Box>
        </Typography>
        <Typography variant="body1" mb={3} color="text.secondary">
          Build Fast, Ship Faster! 🚀<br />This project is set up with Next.js and Material UI.
        </Typography>
        <Button variant="contained" color="primary" size="large" onClick={handleClick} sx={{ mb: 3 }}>
          Click me for a toast notification: {count}
        </Button>
        <Stack direction="row" spacing={2} justifyContent="center" mb={2} mt={2}>
          <Chip label="Material UI" color="primary" />
          <Chip label="Next.js" color="secondary" />
          <Chip label="HackPack" color="success" />
        </Stack>
        <Divider sx={{ my: 2 }} />
        <Typography variant="caption" color="#030303">
          Edit <Box component="span" color={"#030303"} sx={{ bgcolor: 'grey.500', p: 0.5, borderRadius: 1 }}>src/app/page.tsx</Box> to get started
        </Typography>
      </Container>
    </Box>
  );
}
`;
    await fs.writeFile(pagePath, pageContent);
    console.log(chalk.green('Material UI setup completed successfully!'));
  } catch (error) {
    console.error(chalk.red('Error setting up Material UI:'), error.message);
    console.log(chalk.yellow('You may need to set up Material UI manually after project creation.'));
  }
  process.chdir('..');
}
