import { execa } from 'execa';
import chalk from 'chalk';
import fs from 'fs/promises';
import path from 'path';

export async function setupPlainCSS(projectName, languageChoice) {
  console.log(chalk.blue('Setting up plain CSS...'));
  process.chdir(projectName);

  try {
    console.log(chalk.blue('Installing toast component...'));
    await execa('npm', ['install', 'sonner'], { stdio: 'inherit' });

    const globalCssPath = path.join(process.cwd(), 'src', 'app', 'globals.css');
    let css = `body { font-family: system-ui, sans-serif; background: linear-gradient(to bottom, #0f172a, #1e293b); min-height: 100vh; margin: 0; }
.welcome-btn { background: #2563eb; color: #fff; border: none; border-radius: 0.375rem; padding: 0.75rem 1.5rem; font-size: 1rem; font-weight: 500; cursor: pointer; transition: background 0.2s; }
.welcome-btn:hover { background: #1d4ed8; }
.welcome-card { background: rgba(255,255,255,0.04); border-radius: 1rem; box-shadow: 0 4px 24px 0 rgba(0,0,0,0.15); padding: 2.5rem 2rem; max-width: 32rem; margin: 0 auto; text-align: center; }
.welcome-title { font-size: 2.5rem; font-weight: bold; color: #fff; margin-bottom: 1.5rem; }
.welcome-highlight { color: #60a5fa; }
.welcome-desc { color: #cbd5e1; font-size: 1.125rem; margin-bottom: 2rem; }
.welcome-edit { color: #94a3b8; font-size: 0.9rem; margin-top: 2.5rem; }
.welcome-code { background: #334155; color: #fff; padding: 0.2rem 0.5rem; border-radius: 0.3rem; font-family: monospace; }
`;
    try {
      await fs.access(globalCssPath);
    } catch {
      await fs.writeFile(globalCssPath, css, 'utf8');
    }

    const componentsDir = path.join(process.cwd(), 'src', 'components');
    try { await fs.mkdir(componentsDir, { recursive: true }); } catch {}
    const uiComponentsDir = path.join(componentsDir, 'ui');
    try { await fs.mkdir(uiComponentsDir, { recursive: true }); } catch {}
    const toasterPath = path.join(uiComponentsDir, `toaster.${languageChoice === 'ts' ? 'tsx' : 'js'}`);
    const toasterContent = `"use client"\nimport { Toaster as SonnerToaster } from "sonner";\nexport function Toaster() {\n  return (<SonnerToaster position=\"top-right\" richColors closeButton className=\"z-50\" />);\n}\n`;
    await fs.writeFile(toasterPath, toasterContent, 'utf8');

    const layoutPath = `src/app/layout.${languageChoice === 'ts' ? 'tsx' : 'js'}`;
    let layoutContent = await fs.readFile(layoutPath, 'utf8');
    if (!layoutContent.includes('import { Toaster }')) {
      const importRegex = /^import .+?;/gm;
      let match, lastImportIndex = 0;
      while ((match = importRegex.exec(layoutContent)) !== null) {
        lastImportIndex = match.index + match[0].length;
      }
      const toasterImport = 'import { Toaster } from "@/components/ui/toaster";';
      layoutContent = lastImportIndex > 0
        ? layoutContent.slice(0, lastImportIndex) + '\n' + toasterImport + layoutContent.slice(lastImportIndex)
        : toasterImport + '\n' + layoutContent;
    }
    if (!layoutContent.includes('<Toaster />')) {
      if (layoutContent.includes('</body>')) {
        layoutContent = layoutContent.replace('</body>', '        <Toaster />\n      </body>');
      }
    }
    if (layoutContent.includes('title:') && layoutContent.includes('metadata')) {
      layoutContent = layoutContent.replace(/title: ["']Create Next App["']/, 'title: "HackPack Turbo — Build Fast, Ship Faster"');
      if (layoutContent.includes('description:')) {
        layoutContent = layoutContent.replace(/description: ["']Generated by create next app["']/, 'description: "Web application created with HackPack"');
      }
    }
    await fs.writeFile(layoutPath, layoutContent);

    // Create welcome page
    const pagePath = `src/app/page.${languageChoice === 'ts' ? 'tsx' : 'js'}`;
    const pageContent = languageChoice === 'ts' ? `"use client"
import { toast } from "sonner";
import { useState } from "react";
export default function Home() {
  const [count, setCount] = useState(0);
  const handleClick = () => {
    setCount(count + 1);
    toast.success("Success!", {
      description: "You've installed plain CSS with HackPack 🚀",
    });
  };
  return (
  <>
    <main>
      <div className="welcome-card">
        <h1 className="welcome-title">Welcome to <span className="welcome-highlight">HackPack</span></h1>
        <p className="welcome-desc">
          Build Fast, Ship Faster! 🚀<br />This project is set up with Next.js and plain CSS.
        </p>
        <button className="welcome-btn" onClick={handleClick}>
          Click me for a toast notification: {count}
        </button>
        <p className="welcome-edit">
          Edit <span className="welcome-code">src/app/page.tsx</span> to get started
        </p>
      </div>
    </main>
    </>
  );
}
` : `"use client"
import { toast } from "sonner";
import { useState } from "react";
export default function Home() {
  const [count, setCount] = useState(0);
  const handleClick = () => {
    setCount(count + 1);
    toast.success("Success!", {
      description: "You've installed plain CSS with HackPack 🚀",
    });
  };
  return (
  <>
    <main>
      <div className="welcome-card">
        <h1 className="welcome-title">Welcome to <span className="welcome-highlight">HackPack</span></h1>
        <p className="welcome-desc">
          Build Fast, Ship Faster! 🚀<br />This project is set up with Next.js and plain CSS.
        </p>
        <button className="welcome-btn" onClick={handleClick}>
          Click me for a toast notification: {count}
        </button>
        <p className="welcome-edit">
          Edit <span className="welcome-code">src/app/page.js</span> to get started
        </p>
      </div>
    </main>
    </>
  );
}
`;
    await fs.writeFile(pagePath, pageContent);

    // Always overwrite globals.css with the user's provided plain CSS styles
    const hackpackCss = `:root {
--background: #ffffff;
--foreground: #171717;
}

@media (prefers-color-scheme: dark) {
:root {
--background: #0a0a0a;
--foreground: #ededed;
}
}

html,
body {
max-width: 100vw;
overflow-x: hidden;
}

body {
color: var(--foreground);
background: linear-gradient(to bottom, #082166, #bfa391);
font-family: Arial, Helvetica, sans-serif;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
min-height: 100vh;
}

*{
box-sizing: border-box;
padding: 0;
margin: 0;
}
a {
color: inherit;
text-decoration: none;
}

@media (prefers-color-scheme: dark) {
html {
color-scheme: dark;
}
}

/* HackPack Welcome Page Styles */
.welcome-btn {
background: #1f84c2;
color: #fff;
border: none;
border-radius: 0.7rem;
padding: 0.75rem 1rem;
font-size: 1rem;
font-weight: 500;
cursor: pointer;
transition: background 0.2s;
}
.welcome-btn:hover {
background: #18628f;
}
.welcome-card {
background: rgba(255,255,255,0.04);
border-radius: 1rem;
box-shadow: 0 4px 24px 0 rgba(0,0,0,0.15);
padding: 2.5rem 2rem;
max-width: 36rem;
margin: 0 auto;
margin-top: 9rem;
text-align: center;
}
.welcome-title {
font-size: 2.5rem;
font-weight: bold;
color: #fff;
margin-bottom: 1.5rem;
}
.welcome-highlight {
color: #31aaf5;
}
.welcome-desc {
color: #cbd5e1;
font-size: 1.125rem;
margin-bottom: 2rem;
}
.welcome-edit {
color: #cbd5e1;
font-size: 0.9rem;
margin-top: 2.5rem;
}
.welcome-code {
background: #334155;
color: #fff;
padding: 0.2rem 0.5rem;
border-radius: 0.3rem;
font-family: monospace;
}
`;
    await fs.writeFile(globalCssPath, hackpackCss, 'utf8');

    console.log(chalk.green('Plain CSS setup completed successfully!'));
  } catch (error) {
    console.error(chalk.red('Error setting up plain CSS:'), error.message);
    console.log(chalk.yellow('You may need to set up plain CSS manually after project creation.'));
  }
  process.chdir('..');
}
